IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'RAP' AND t.name = 'GENERIC_REF_TBL')
BEGIN
    CREATE TABLE [RAP].[GENERIC_REF_TBL](
        [GENERIC_REF_TBL_ID] [int] IDENTITY(1,1) PRIMARY KEY,
        [GENERIC_REF_TBL_PARENT_ID] [int] NULL,
        [GENERIC_REF_TBL_NM] [varchar](50) NOT NULL,
        [GENERIC_REF_TBL_CODE] [varchar](50) NOT NULL,
        [GENERIC_REF_TBL_DESC] [varchar](max) NULL,
    CONSTRAINT FK1_GENERIC_REF_TBL FOREIGN KEY (GENERIC_REF_TBL_PARENT_ID) 
            REFERENCES RAP.GENERIC_REF_TBL(GENERIC_REF_TBL_ID) ON DELETE NO ACTION);
    PRINT 'Created RAP.GENERIC_REF_TBL Table';
END
ELSE
    PRINT 'Table RAP.GENERIC_REF_TBL already exists';
GO


IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'RAP' AND t.name = 'WORKFLOW_APP_ASSOC')
BEGIN
    CREATE TABLE [RAP].[WORKFLOW_APP_ASSOC](
        [PROCESSINSTANCEID] [bigint] NOT NULL,
        [APP_ID] [BIGINT] NOT NULL,
        [CREATED_BY] [BIGINT] NOT NULL,
        [MODIFIED_BY] [BIGINT] NOT NULL,
        [CREATE_DT] [datetime] NOT NULL CONSTRAINT [DF_WORKFLOW_APP_ASSOC_CREATE_DT] DEFAULT (getdate()),
        [MODIFY_DT] [datetime] NOT NULL CONSTRAINT [DF_WORKFLOW_APP_ASSOC_MODIFY_DT] DEFAULT (getdate()),
        [DELETE_YN] [char](1) NOT NULL CONSTRAINT [DF_WORKFLOW_APP_ASSOC_DELETE_YN] DEFAULT ('N'),
        [STATUS_CD] [int] NULL,
    CONSTRAINT [FK_WORKFLOW_APP_ASSOC_APPLICATION] FOREIGN KEY([APP_ID])      REFERENCES [RAP].[APPLICATION] ([ID]),
    CONSTRAINT [FK_WORKFLOW_APP_ASSOC_CREATED_BY]  FOREIGN KEY([CREATED_BY])  REFERENCES [RAP].[USER_INFO] ([ID]),
    CONSTRAINT [FK_WORKFLOW_APP_ASSOC_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY]) REFERENCES [RAP].[USER_INFO] ([ID]),
    CONSTRAINT [FK_WORKFLOW_APP_ASSOC_STATUS_CD]   FOREIGN KEY([STATUS_CD])   REFERENCES [RAP].[GENERIC_REF_TBL] ([GENERIC_REF_TBL_ID])
    );
    PRINT 'Created RAP.WORKFLOW_APP_ASSOC Table';
END
ELSE
    PRINT 'Table RAP.WORKFLOW_APP_ASSOC already exists';
GO

