
IF NOT EXISTS (SELECT 1 FROM sys.views t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'RAP' AND t.name = 'GENERIC_REF_TBL')
BEGIN
    CREATE TABLE [RAP].[GENERIC_REF_TBL](
        [GENERIC_REF_TBL_ID] [int] NOT NULL,
        [GENERIC_REF_TBL_PARENT_ID] [int] NULL,
        [GENERIC_REF_TBL_NM] [varchar](50) NOT NULL,
        [GENERIC_REF_TBL_CODE] [varchar](50) NOT NULL,
        [GENERIC_REF_TBL_DESC] [varchar](max) NULL,
    CONSTRAINT [PK_GENERIC_REF_TBL] PRIMARY KEY CLUSTERED (
        [GENERIC_REF_TBL_ID] ASC));
    ALTER TABLE [GLOBALX].[GENERIC_REF_TBL]  WITH CHECK ADD  CONSTRAINT [FK1_GENERIC_REF_TBL] FOREIGN KEY([GENERIC_REF_TBL_PARENT_ID])
        REFERENCES [GLOBALX].[GENERIC_REF_TBL] ([GENERIC_REF_TBL_ID]);
    ALTER TABLE [GLOBALX].[GENERIC_REF_TBL] CHECK CONSTRAINT [FK1_GENERIC_REF_TBL]
    PRINT 'Created RAP.GENERIC_REF_TBL Table';
END
ELSE
    PRINT 'Table RAP.GENERIC_REF_TBL already exists';
GO


IF NOT EXISTS (SELECT 1 FROM sys.views t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'RAP' AND t.name = 'WORKFLOW_APP_ASSOC')
BEGIN
    CREATE TABLE [RAP].[WORKFLOW_APP_ASSOC](
        [PROCESSINSTANCEID] [bigint] NOT NULL,
        [APP_ID] [int] NOT NULL,
        [CREATED_BY] [int] NOT NULL,
        [MODIFIED_BY] [int] NOT NULL,
        [CREATE_DT] [datetime] NOT NULL,
        [MODIFY_DT] [datetime] NOT NULL,
        [DELETE_YN] [char](1) NOT NULL,
        [STATUS_CD] [int] NULL
    ) ON [PRIMARY];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC] ADD  CONSTRAINT [DF_WORKFLOW_APP_ASSOC_CREATE_DT]  DEFAULT (getdate()) FOR [CREATE_DT];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC] ADD  CONSTRAINT [DF_WORKFLOW_APP_ASSOC_MODIFY_DT]  DEFAULT (getdate()) FOR [MODIFY_DT];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC] ADD  CONSTRAINT [DF_WORKFLOW_APP_ASSOC_DELETE_YN]  DEFAULT ('N') FOR [DELETE_YN];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_APP_ASSOC_APPLICATION] FOREIGN KEY([APP_ID])
    REFERENCES [RAP].[APPLICATION] ([ID]);
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC] CHECK CONSTRAINT [FK_WORKFLOW_APP_ASSOC_APPLICATION];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_APP_ASSOC_CREATED_BY] FOREIGN KEY([CREATED_BY])
    REFERENCES [RAP].[USER_INFO] ([ID]);
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC] CHECK CONSTRAINT [FK_WORKFLOW_APP_ASSOC_CREATED_BY];
    ALTER TABLE [RAP].[WORKFLOW_APP_ASSOC]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_APP_ASSOC_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY])
    REFERENCES [RAP].[USER_INFO] ([ID]);
    ALTER TABLE [RAPTOR].[WORKFLOW_APP_ASSOC] CHECK CONSTRAINT [FK_WORKFLOW_APP_ASSOC_MODIFIED_BY];
    ALTER TABLE [RAPTOR].[WORKFLOW_APP_ASSOC]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_APP_ASSOC_STATUS_CD] FOREIGN KEY([STATUS_CD])
    REFERENCES [RAP].[GENERIC_REF_TBL] ([GENERIC_REF_TBL_ID]);
    ALTER TABLE [RAPTOR].[WORKFLOW_APP_ASSOC] CHECK CONSTRAINT [FK_WORKFLOW_APP_ASSOC_STATUS_CD];
    PRINT 'Created RAP.WORKFLOW_APP_ASSOC Table';
END
ELSE
    PRINT 'Table RAP.WORKFLOW_APP_ASSOC already exists';
GO

