-- Seed universities
IF NOT EXISTS (SELECT 1 FROM RAP.GENERIC_REF_TBL WHERE GENERIC_REF_TBL_NM = 'PERMIT_STATUS_CD' AND GENERIC_REF_TBL_CODE = 'PENDING')
    INSERT INTO RAP.GENERIC_REF_TBL (GENERIC_REF_TBL_NM, GENERIC_REF_TBL_CODE, GENERIC_REF_TBL_DESC) VALUES ('PERMIT_STATUS_CD', 'PENDING_SUBMIT', 'Pending Submission');

IF NOT EXISTS (SELECT 1 FROM RAP.GENERIC_REF_TBL WHERE GENERIC_REF_TBL_NM = 'PERMIT_STATUS_CD' AND GENERIC_REF_TBL_CODE = 'ACCEPTED')
    INSERT INTO RAP.GENERIC_REF_TBL (GENERIC_REF_TBL_NM, GENERIC_REF_TBL_CODE, GENERIC_REF_TBL_DESC) VALUES ('PERMIT_STATUS_CD', 'ACCEPTED', 'Accepted');
