-- Seed GENERIC_REF_TBL

IF NOT EXISTS (SELECT 1 FROM RAP.GENERIC_REF_TBL WHERE GENERIC_REF_TBL_NM = 'PERMIT_STATUS_CD' AND GENERIC_REF_TBL_CODE = 'PENDING')
    INSERT INTO RAP.GENERIC_REF_TBL (GENERIC_REF_TBL_NM, GENERIC_REF_TBL_CODE, GENERIC_REF_TBL_DESC) VALUES ('APPLICATION_STATUS_CD', 'PENDING_SUBMIT', 'Pending');

IF NOT EXISTS (SELECT 1 FROM RAP.GENERIC_REF_TBL WHERE GENERIC_REF_TBL_NM = 'APPLICATION_STATUS_CD' AND GENERIC_REF_TBL_CODE = 'SUBMITTED')
    INSERT INTO RAP.GENERIC_REF_TBL (GENERIC_REF_TBL_NM, GENERIC_REF_TBL_CODE, GENERIC_REF_TBL_DESC) VALUES ('APPLICATION_STATUS_CD', 'SUBMITTED', 'Submitted');

IF NOT EXISTS (SELECT 1 FROM RAP.GENERIC_REF_TBL WHERE GENERIC_REF_TBL_NM = 'PERMIT_STATUS_CD' AND GENERIC_REF_TBL_CODE = 'ACCEPTED')
    INSERT INTO RAP.GENERIC_REF_TBL (GENERIC_REF_TBL_NM, GENERIC_REF_TBL_CODE, GENERIC_REF_TBL_DESC) VALUES ('APPLICATION_STATUS_CD', 'ACCEPTED', 'Accepted');
